spring.application.name=projectBackend
spring.datasource.url=jdbc:mysql://localhost:3306/Backend_db
spring.datasource.username=root
spring.datasource.password=anwar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

